//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.29 at 09:51:23 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.niso.org/schemas/counter", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ubl.amsl.technology.counter.model.version4_1;
