//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.29 at 09:51:52 AM CEST 
//


package ubl.amsl.technology.counter.model.version4_1.elements;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AttributeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AttributeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ArticleVersion"/>
 *     &lt;enumeration value="ArticleType"/>
 *     &lt;enumeration value="QualificationName"/>
 *     &lt;enumeration value="QualificationLevel"/>
 *     &lt;enumeration value="Proprietary"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AttributeType", namespace = "http://www.niso.org/schemas/counter")
@XmlEnum
public enum AttributeType {

    @XmlEnumValue("ArticleVersion")
    ARTICLE_VERSION("ArticleVersion"),
    @XmlEnumValue("ArticleType")
    ARTICLE_TYPE("ArticleType"),
    @XmlEnumValue("QualificationName")
    QUALIFICATION_NAME("QualificationName"),
    @XmlEnumValue("QualificationLevel")
    QUALIFICATION_LEVEL("QualificationLevel"),
    @XmlEnumValue("Proprietary")
    PROPRIETARY("Proprietary");
    private final String value;

    AttributeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AttributeType fromValue(String v) {
        for (AttributeType c: AttributeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
