//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.29 at 09:51:52 AM CEST 
//


package ubl.amsl.technology.counter.model.version4_1.elements;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContributorIdentifierType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ContributorIdentifierType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ISNI"/>
 *     &lt;enumeration value="ORCID"/>
 *     &lt;enumeration value="Name"/>
 *     &lt;enumeration value="Proprietary"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ContributorIdentifierType", namespace = "http://www.niso.org/schemas/counter")
@XmlEnum
public enum ContributorIdentifierType {

    ISNI("ISNI"),
    ORCID("ORCID"),
    @XmlEnumValue("Name")
    NAME("Name"),
    @XmlEnumValue("Proprietary")
    PROPRIETARY("Proprietary");
    private final String value;

    ContributorIdentifierType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ContributorIdentifierType fromValue(String v) {
        for (ContributorIdentifierType c: ContributorIdentifierType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
